import type {Metadata} from 'next';
import {Mulish} from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';

const mulish = Mulish({subsets: ['latin'], weight: ['500']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={mulish.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
