import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import {ProviderLayout} from '@/components/Provider/Provider';
import Search from '@/components/Search/Search';

const inter = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Eat wist',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProviderLayout>
      <html lang='en'>
        <body className={inter.className}>
          <Header></Header>
          <Search />
          {children}
        </body>
      </html>
    </ProviderLayout>
  );
}
