import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';

const inter = Roboto({weight: '400', subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
